# API 키 설정
# Streamlit Cloud에서는 대시보드에서 이러한 값을 설정하세요

# OpenAI API 키
OPENAI_API_KEY = "your-openai-api-key-here"

# Anthropic API 키
ANTHROPIC_API_KEY = "your-anthropic-api-key-here"

# Google Gemini API 키
GOOGLE_API_KEY = "your-google-api-key-here"

# DeepSeek API 키
DEEPSEEK_API_KEY = "your-deepseek-api-key-here"

# Grok API 키 (x.ai)
GROK_API_KEY = "your-grok-api-key-here" 